version: '1'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      bootstrap.memory_lock: true
    networks:
      - elk

  kibana:
    container_name: kibana
    build:
      context: kibana/
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge