# 7.10.2 OSS Version
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Add Plugin
# RUN elasticsearch-plugin install analysis-nori